using System.ComponentModel.DataAnnotations.Schema;

namespace Quest;

/// <summary>
/// Leaf node representing a quality assessment.
/// </summary>
public class QualityAssessment
{
  /// <summary>
  /// Autogenerated unique identifier for the quality node.
  /// </summary>
  [Key]
  [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
  public int Id { get; set; }


  /// <summary>
  /// Navigation property to the parent quality assessment.
  /// </summary>
  public required  QualityAssessment Assessment { get; set;}

  /// <summary>
  /// Foreign key to the Evaluator person.
  /// </summary>
  public int EvaluatorId { get; set; }

  /// <summary>
  /// Assessed grade value.
  /// </summary>
  [MaxLength(10)]
  public string? Grade { get; set; }
}