namespace Quest;

/// <summary>
/// Represents an abstract node of a quality tree.
/// </summary>
public abstract class QualityNode : QualityObject
{
  ///// <summary>
  ///// Autogenerated unique identifier for the quality node.
  ///// </summary>
  //[Key]
  //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
  //public int Id { get; set; }

  /// <summary>
  ///  Level of the quality node in the tree (0 for root, 1 for factor).
  /// </summary>
  public int Level
  {
    get
    {
      if (GetType() == typeof(QualityFactor))
        return 1;
      if (Parent is QualityNode parentNode)
      {
        return parentNode.Level + 1;
      }
      return 0;
    }
  }

  /// <summary>
  /// Order of the quality node among its siblings.
  /// </summary>
  [DefaultValue(0)]
  public int Ord { get; set; }

  /// <summary>
  /// Name of the quality node.
  /// </summary>
  [MaxLength(255)]
  public string? Name { get; set; }

  /// <summary>
  /// Display text of the quality node.
  /// </summary>
  [MaxLength(255)]
  public string? Text { get; set; }

  /// <summary>
  /// Weight of the quality value in overall assessment.
  /// </summary>
  public int Weight { get; set; } = 10;

  /// <summary>
  /// A short comment or description about the quality node.
  /// </summary>
  [MaxLength(255)]
  public string? Comment { get; set; }

  /// <summary>
  /// Gets or sets the parent node associated with this quality metrics node.
  /// </summary>
  [XmlIgnore]
  public QualityMetricsNode? Parent { get; set; }
}