//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestRSX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Factors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Factors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestRSX.Factors", typeof(Factors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness.
        /// </summary>
        internal static string Completeness {
            get {
                return ResourceManager.GetString("Completeness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the degree to which all necessary elements are present..
        /// </summary>
        internal static string CompletenessDescription {
            get {
                return ResourceManager.GetString("CompletenessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency.
        /// </summary>
        internal static string Consistency {
            get {
                return ResourceManager.GetString("Consistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the uniformity and coherence of information across different elements or documents..
        /// </summary>
        internal static string ConsistencyDescription {
            get {
                return ResourceManager.GetString("ConsistencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctness.
        /// </summary>
        internal static string Correctness {
            get {
                return ResourceManager.GetString("Correctness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the degree to which the given information is correct and free from errors..
        /// </summary>
        internal static string CorrectnessDescription {
            get {
                return ResourceManager.GetString("CorrectnessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiability.
        /// </summary>
        internal static string Modifiability {
            get {
                return ResourceManager.GetString("Modifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how easily information can be changed or adapted when necessary..
        /// </summary>
        internal static string ModifiabilityDescription {
            get {
                return ResourceManager.GetString("ModifiabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understandability.
        /// </summary>
        internal static string Understandability {
            get {
                return ResourceManager.GetString("Understandability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how easily information can be understood by the intended audience..
        /// </summary>
        internal static string UnderstandabilityDescription {
            get {
                return ResourceManager.GetString("UnderstandabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifiability.
        /// </summary>
        internal static string Verifiability {
            get {
                return ResourceManager.GetString("Verifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the degree to which provisions can be verified for completeness and correctness..
        /// </summary>
        internal static string VerifialibilityDescription {
            get {
                return ResourceManager.GetString("VerifialibilityDescription", resourceCulture);
            }
        }
    }
}
