//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestRSX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetricsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetricsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestRSX.MetricsStrings", typeof(MetricsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptability.
        /// </summary>
        public static string Acceptability {
            get {
                return ResourceManager.GetString("Acceptability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string Acceptance {
            get {
                return ResourceManager.GetString("Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity model completeness.
        /// </summary>
        public static string ActivityModelCompleteness {
            get {
                return ResourceManager.GetString("ActivityModelCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional descriptions.
        /// </summary>
        public static string AdditionalDescriptions {
            get {
                return ResourceManager.GetString("AdditionalDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adequacy.
        /// </summary>
        public static string Adequacy {
            get {
                return ResourceManager.GetString("Adequacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity of descriptions.
        /// </summary>
        public static string ClarityOfDescriptions {
            get {
                return ResourceManager.GetString("ClarityOfDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class generalization completeness.
        /// </summary>
        public static string ClassGeneralizationCompleteness {
            get {
                return ResourceManager.GetString("ClassGeneralizationCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class identification completeness.
        /// </summary>
        public static string ClassIdentificationCompleteness {
            get {
                return ResourceManager.GetString("ClassIdentificationCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class model completeness.
        /// </summary>
        public static string ClassModelCompleteness {
            get {
                return ResourceManager.GetString("ClassModelCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class specification completeness.
        /// </summary>
        public static string ClassSpecificationCompleteness {
            get {
                return ResourceManager.GetString("ClassSpecificationCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility with experience.
        /// </summary>
        public static string CompatibilityWithExperience {
            get {
                return ResourceManager.GetString("CompatibilityWithExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete identification of state machines.
        /// </summary>
        public static string CompleteIdentificationOfStateMachines {
            get {
                return ResourceManager.GetString("CompleteIdentificationOfStateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness meets shareholder requirements.
        /// </summary>
        public static string CompletenessMeetsShareholderRequirements {
            get {
                return ResourceManager.GetString("CompletenessMeetsShareholderRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness meets user requirements.
        /// </summary>
        public static string CompletenessMeetsUserRequirements {
            get {
                return ResourceManager.GetString("CompletenessMeetsUserRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of activity identification.
        /// </summary>
        public static string CompletenessOfActivityIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfActivityIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of activity specifications.
        /// </summary>
        public static string CompletenessOfActivitySpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfActivitySpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of actor generalizations.
        /// </summary>
        public static string CompletenessOfActorGeneralizations {
            get {
                return ResourceManager.GetString("CompletenessOfActorGeneralizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of actor identification.
        /// </summary>
        public static string CompletenessOfActorIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfActorIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of actors.
        /// </summary>
        public static string CompletenessOfActors {
            get {
                return ResourceManager.GetString("CompletenessOfActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of actor specifications.
        /// </summary>
        public static string CompletenessOfActorSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfActorSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of aggregation declarations.
        /// </summary>
        public static string CompletenessOfAggregationDeclarations {
            get {
                return ResourceManager.GetString("CompletenessOfAggregationDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of assignment of classes to components.
        /// </summary>
        public static string CompletenessOfAssignmentOfClassesToComponents {
            get {
                return ResourceManager.GetString("CompletenessOfAssignmentOfClassesToComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of association declaration.
        /// </summary>
        public static string CompletenessOfAssociationDeclaration {
            get {
                return ResourceManager.GetString("CompletenessOfAssociationDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of capability specification.
        /// </summary>
        public static string CompletenessOfCapabilitySpecification {
            get {
                return ResourceManager.GetString("CompletenessOfCapabilitySpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of class capability definitions.
        /// </summary>
        public static string CompletenessOfClassCapabilityDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfClassCapabilityDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of class capability identification.
        /// </summary>
        public static string CompletenessOfClassCapabilityIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfClassCapabilityIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of class definitions.
        /// </summary>
        public static string CompletenessOfClassDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfClassDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of class property definitions.
        /// </summary>
        public static string CompletenessOfClassPropertyDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfClassPropertyDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of class property identification.
        /// </summary>
        public static string CompletenessOfClassPropertyIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfClassPropertyIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of component definitions.
        /// </summary>
        public static string CompletenessOfComponentDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfComponentDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of component identification.
        /// </summary>
        public static string CompletenessOfComponentIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfComponentIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of component specifications.
        /// </summary>
        public static string CompletenessOfComponentSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfComponentSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of condition machines.
        /// </summary>
        public static string CompletenessOfConditionMachines {
            get {
                return ResourceManager.GetString("CompletenessOfConditionMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of control definitions.
        /// </summary>
        public static string CompletenessOfControlDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfControlDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of control specifications.
        /// </summary>
        public static string CompletenessOfControlSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfControlSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of data definitions.
        /// </summary>
        public static string CompletenessOfDataDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfDataDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of data structure definitions.
        /// </summary>
        public static string CompletenessOfDataStructureDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfDataStructureDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of data structure identification.
        /// </summary>
        public static string CompletenessOfDataStructureIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfDataStructureIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of definition.
        /// </summary>
        public static string CompletenessOfDefinition {
            get {
                return ResourceManager.GetString("CompletenessOfDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of diagrams.
        /// </summary>
        public static string CompletenessOfDiagrams {
            get {
                return ResourceManager.GetString("CompletenessOfDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of dialogue definitions.
        /// </summary>
        public static string CompletenessOfDialogueDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfDialogueDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of documentation.
        /// </summary>
        public static string CompletenessOfDocumentation {
            get {
                return ResourceManager.GetString("CompletenessOfDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of event identification.
        /// </summary>
        public static string CompletenessOfEventIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfEventIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of event specifications.
        /// </summary>
        public static string CompletenessOfEventSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfEventSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of flow.
        /// </summary>
        public static string CompletenessOfFlow {
            get {
                return ResourceManager.GetString("CompletenessOfFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of form definitions.
        /// </summary>
        public static string CompletenessOfFormDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfFormDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of form designs.
        /// </summary>
        public static string CompletenessOfFormDesigns {
            get {
                return ResourceManager.GetString("CompletenessOfFormDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of form specifications.
        /// </summary>
        public static string CompletenessOfFormSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfFormSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of function definitions.
        /// </summary>
        public static string CompletenessOfFunctionDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfFunctionDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of function implementation.
        /// </summary>
        public static string CompletenessOfFunctionImplementation {
            get {
                return ResourceManager.GetString("CompletenessOfFunctionImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of generalization of use cases.
        /// </summary>
        public static string CompletenessOfGeneralizationOfUseCases {
            get {
                return ResourceManager.GetString("CompletenessOfGeneralizationOfUseCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of goal achievement.
        /// </summary>
        public static string CompletenessOfGoalAchievement {
            get {
                return ResourceManager.GetString("CompletenessOfGoalAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of goal definitions.
        /// </summary>
        public static string CompletenessOfGoalDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfGoalDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interaction identification.
        /// </summary>
        public static string CompletenessOfInteractionIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfInteractionIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interaction model.
        /// </summary>
        public static string CompletenessOfInteractionModel {
            get {
                return ResourceManager.GetString("CompletenessOfInteractionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interactions.
        /// </summary>
        public static string CompletenessOfInteractions {
            get {
                return ResourceManager.GetString("CompletenessOfInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interaction specifications.
        /// </summary>
        public static string CompletenessOfInteractionSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfInteractionSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interaction stakeholders.
        /// </summary>
        public static string CompletenessOfInteractionStakeholders {
            get {
                return ResourceManager.GetString("CompletenessOfInteractionStakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interface definitions.
        /// </summary>
        public static string CompletenessOfInterfaceDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfInterfaceDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of interface implementations.
        /// </summary>
        public static string CompletenessOfInterfaceImplementations {
            get {
                return ResourceManager.GetString("CompletenessOfInterfaceImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of liability identification.
        /// </summary>
        public static string CompletenessOfLiabilityIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfLiabilityIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of machine specifications.
        /// </summary>
        public static string CompletenessOfMachineSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfMachineSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of message identification.
        /// </summary>
        public static string CompletenessOfMessageIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfMessageIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of messages.
        /// </summary>
        public static string CompletenessOfMessages {
            get {
                return ResourceManager.GetString("CompletenessOfMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of navigation diagrams.
        /// </summary>
        public static string CompletenessOfNavigationDiagrams {
            get {
                return ResourceManager.GetString("CompletenessOfNavigationDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of pass specifications.
        /// </summary>
        public static string CompletenessOfPassSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfPassSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of processing definitions.
        /// </summary>
        public static string CompletenessOfProcessingDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfProcessingDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of processing implementation.
        /// </summary>
        public static string CompletenessOfProcessingImplementation {
            get {
                return ResourceManager.GetString("CompletenessOfProcessingImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of property specification.
        /// </summary>
        public static string CompletenessOfPropertySpecification {
            get {
                return ResourceManager.GetString("CompletenessOfPropertySpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of relationship definitions.
        /// </summary>
        public static string CompletenessOfRelationshipDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfRelationshipDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of relationship specification.
        /// </summary>
        public static string CompletenessOfRelationshipSpecification {
            get {
                return ResourceManager.GetString("CompletenessOfRelationshipSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of report definitions.
        /// </summary>
        public static string CompletenessOfReportDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfReportDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of report designs.
        /// </summary>
        public static string CompletenessOfReportDesigns {
            get {
                return ResourceManager.GetString("CompletenessOfReportDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of report specifications.
        /// </summary>
        public static string CompletenessOfReportSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfReportSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of shareholders definition.
        /// </summary>
        public static string CompletenessOfShareholdersDefinition {
            get {
                return ResourceManager.GetString("CompletenessOfShareholdersDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of state identification.
        /// </summary>
        public static string CompletenessOfStateIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfStateIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of state specifications.
        /// </summary>
        public static string CompletenessOfStateSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfStateSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of structure specifications.
        /// </summary>
        public static string CompletenessOfStructureSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfStructureSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of system definition.
        /// </summary>
        public static string CompletenessOfSystemDefinition {
            get {
                return ResourceManager.GetString("CompletenessOfSystemDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of system implementation.
        /// </summary>
        public static string CompletenessOfSystemImplementation {
            get {
                return ResourceManager.GetString("CompletenessOfSystemImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of transition definitions.
        /// </summary>
        public static string CompletenessOfTransitionDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfTransitionDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of type definitions.
        /// </summary>
        public static string CompletenessOfTypeDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfTypeDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case definitions.
        /// </summary>
        public static string CompletenessOfUseCaseDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case extension.
        /// </summary>
        public static string CompletenessOfUseCaseExtension {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case identification.
        /// </summary>
        public static string CompletenessOfUseCaseIdentification {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case incorporating.
        /// </summary>
        public static string CompletenessOfUseCaseIncorporating {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseIncorporating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case model.
        /// </summary>
        public static string CompletenessOfUseCaseModel {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of use case specifications.
        /// </summary>
        public static string CompletenessOfUseCaseSpecifications {
            get {
                return ResourceManager.GetString("CompletenessOfUseCaseSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of user definitions.
        /// </summary>
        public static string CompletenessOfUserDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfUserDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of user interface definitions.
        /// </summary>
        public static string CompletenessOfUserInterfaceDefinitions {
            get {
                return ResourceManager.GetString("CompletenessOfUserInterfaceDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completeness of user interface design.
        /// </summary>
        public static string CompletenessOfUserInterfaceDesign {
            get {
                return ResourceManager.GetString("CompletenessOfUserInterfaceDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component model completeness.
        /// </summary>
        public static string ComponentModelCompleteness {
            get {
                return ResourceManager.GetString("ComponentModelCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurability.
        /// </summary>
        public static string Configurability {
            get {
                return ResourceManager.GetString("Configurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of activity model and behavioral model.
        /// </summary>
        public static string ConsistencyOfActivityModelAndBehavioralModel {
            get {
                return ResourceManager.GetString("ConsistencyOfActivityModelAndBehavioralModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of activity model and class model.
        /// </summary>
        public static string ConsistencyOfActivityModelAndClassModel {
            get {
                return ResourceManager.GetString("ConsistencyOfActivityModelAndClassModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of activity model and requirements specifications.
        /// </summary>
        public static string ConsistencyOfActivityModelAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfActivityModelAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of activity model and use case model.
        /// </summary>
        public static string ConsistencyOfActivityModelAndUseCaseModel {
            get {
                return ResourceManager.GetString("ConsistencyOfActivityModelAndUseCaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of class model and functional model.
        /// </summary>
        public static string ConsistencyOfClassModelAndFunctionalModel {
            get {
                return ResourceManager.GetString("ConsistencyOfClassModelAndFunctionalModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of class model and requirements specifications.
        /// </summary>
        public static string ConsistencyOfClassModelAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfClassModelAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of class model and static model.
        /// </summary>
        public static string ConsistencyOfClassModelAndStaticModel {
            get {
                return ResourceManager.GetString("ConsistencyOfClassModelAndStaticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of component model and requirements specifications.
        /// </summary>
        public static string ConsistencyOfComponentModelAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfComponentModelAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of functional model and class model.
        /// </summary>
        public static string ConsistencyOfFunctionalModelAndClassModel {
            get {
                return ResourceManager.GetString("ConsistencyOfFunctionalModelAndClassModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of goals and requirements.
        /// </summary>
        public static string ConsistencyOfGoalsAndRequirements {
            get {
                return ResourceManager.GetString("ConsistencyOfGoalsAndRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of interaction model and behavioral model.
        /// </summary>
        public static string ConsistencyOfInteractionModelAndBehavioralModel {
            get {
                return ResourceManager.GetString("ConsistencyOfInteractionModelAndBehavioralModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of interaction model and class model.
        /// </summary>
        public static string ConsistencyOfInteractionModelAndClassModel {
            get {
                return ResourceManager.GetString("ConsistencyOfInteractionModelAndClassModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of interaction model and dynamic model.
        /// </summary>
        public static string ConsistencyOfInteractionModelAndDynamicModel {
            get {
                return ResourceManager.GetString("ConsistencyOfInteractionModelAndDynamicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of interaction model and requirements specification.
        /// </summary>
        public static string ConsistencyOfInteractionModelAndRequirementsSpecification {
            get {
                return ResourceManager.GetString("ConsistencyOfInteractionModelAndRequirementsSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of interaction model and use case model.
        /// </summary>
        public static string ConsistencyOfInteractionModelAndUseCaseModel {
            get {
                return ResourceManager.GetString("ConsistencyOfInteractionModelAndUseCaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of state model and requirements specifications.
        /// </summary>
        public static string ConsistencyOfStateModelAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfStateModelAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of ui design and requirements specifications.
        /// </summary>
        public static string ConsistencyOfUiDesignAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfUiDesignAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistency of use case model and requirements specifications.
        /// </summary>
        public static string ConsistencyOfUseCaseModelAndRequirementsSpecifications {
            get {
                return ResourceManager.GetString("ConsistencyOfUseCaseModelAndRequirementsSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractual collateral.
        /// </summary>
        public static string ContractualCollateral {
            get {
                return ResourceManager.GetString("ContractualCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctness of documentation.
        /// </summary>
        public static string CorrectnessOfDocumentation {
            get {
                return ResourceManager.GetString("CorrectnessOfDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credibility.
        /// </summary>
        public static string Credibility {
            get {
                return ResourceManager.GetString("Credibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical situations.
        /// </summary>
        public static string CriticalSituations {
            get {
                return ResourceManager.GetString("CriticalSituations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data errors.
        /// </summary>
        public static string DataErrors {
            get {
                return ResourceManager.GetString("DataErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data implementation completeness.
        /// </summary>
        public static string DataImplementationCompleteness {
            get {
                return ResourceManager.GetString("DataImplementationCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model and requirements specification consistency.
        /// </summary>
        public static string DataModelAndRequirementsSpecificationConsistency {
            get {
                return ResourceManager.GetString("DataModelAndRequirementsSpecificationConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model and static model consistency.
        /// </summary>
        public static string DataModelAndStaticModelConsistency {
            get {
                return ResourceManager.GetString("DataModelAndStaticModelConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model completeness.
        /// </summary>
        public static string DataModelCompleteness {
            get {
                return ResourceManager.GetString("DataModelCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model internal consistency.
        /// </summary>
        public static string DataModelInternalConsistency {
            get {
                return ResourceManager.GetString("DataModelInternalConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data modifiability.
        /// </summary>
        public static string DataModifiability {
            get {
                return ResourceManager.GetString("DataModifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data portability.
        /// </summary>
        public static string DataPortability {
            get {
                return ResourceManager.GetString("DataPortability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data scalability.
        /// </summary>
        public static string DataScalability {
            get {
                return ResourceManager.GetString("DataScalability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data size.
        /// </summary>
        public static string DataSize {
            get {
                return ResourceManager.GetString("DataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data testability.
        /// </summary>
        public static string DataTestability {
            get {
                return ResourceManager.GetString("DataTestability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation comprehensibility.
        /// </summary>
        public static string DocumentationComprehensibility {
            get {
                return ResourceManager.GetString("DocumentationComprehensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of appeal in further work.
        /// </summary>
        public static string EaseOfAppealInFurtherWork {
            get {
                return ResourceManager.GetString("EaseOfAppealInFurtherWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of learning.
        /// </summary>
        public static string EaseOfLearning {
            get {
                return ResourceManager.GetString("EaseOfLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of reference.
        /// </summary>
        public static string EaseOfReference {
            get {
                return ResourceManager.GetString("EaseOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of use.
        /// </summary>
        public static string EaseOfUse {
            get {
                return ResourceManager.GetString("EaseOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease of verification.
        /// </summary>
        public static string EaseOfVerification {
            get {
                return ResourceManager.GetString("EaseOfVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptional situations.
        /// </summary>
        public static string ExceptionalSituations {
            get {
                return ResourceManager.GetString("ExceptionalSituations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time.
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediency.
        /// </summary>
        public static string Expediency {
            get {
                return ResourceManager.GetString("Expediency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures.
        /// </summary>
        public static string Failures {
            get {
                return ResourceManager.GetString("Failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault tolerance.
        /// </summary>
        public static string FaultTolerance {
            get {
                return ResourceManager.GetString("FaultTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility.
        /// </summary>
        public static string Flexibility {
            get {
                return ResourceManager.GetString("Flexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility of requirements.
        /// </summary>
        public static string FlexibilityOfRequirements {
            get {
                return ResourceManager.GetString("FlexibilityOfRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formal correctness.
        /// </summary>
        public static string FormalCorrectness {
            get {
                return ResourceManager.GetString("FormalCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formal modifiability.
        /// </summary>
        public static string FormalModifiability {
            get {
                return ResourceManager.GetString("FormalModifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional completeness.
        /// </summary>
        public static string FunctionalCompleteness {
            get {
                return ResourceManager.GetString("FunctionalCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional consistency.
        /// </summary>
        public static string FunctionalConsistency {
            get {
                return ResourceManager.GetString("FunctionalConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional correctness.
        /// </summary>
        public static string FunctionalCorrectness {
            get {
                return ResourceManager.GetString("FunctionalCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional intelligibility.
        /// </summary>
        public static string FunctionalIntelligibility {
            get {
                return ResourceManager.GetString("FunctionalIntelligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality.
        /// </summary>
        public static string Functionality {
            get {
                return ResourceManager.GetString("Functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional reliability.
        /// </summary>
        public static string FunctionalReliability {
            get {
                return ResourceManager.GetString("FunctionalReliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware portability.
        /// </summary>
        public static string HardwarePortability {
            get {
                return ResourceManager.GetString("HardwarePortability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware stability.
        /// </summary>
        public static string HardwareStability {
            get {
                return ResourceManager.GetString("HardwareStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to describe.
        /// </summary>
        public static string HowToDescribe {
            get {
                return ResourceManager.GetString("HowToDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immutability of goals.
        /// </summary>
        public static string ImmutabilityOfGoals {
            get {
                return ResourceManager.GetString("ImmutabilityOfGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation configurability.
        /// </summary>
        public static string InstallationConfigurability {
            get {
                return ResourceManager.GetString("InstallationConfigurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface measures.
        /// </summary>
        public static string InterfaceMeasures {
            get {
                return ResourceManager.GetString("InterfaceMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal connections.
        /// </summary>
        public static string InternalConnections {
            get {
                return ResourceManager.GetString("InternalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of activity model.
        /// </summary>
        public static string InternalConsistencyOfActivityModel {
            get {
                return ResourceManager.GetString("InternalConsistencyOfActivityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of class model.
        /// </summary>
        public static string InternalConsistencyOfClassModel {
            get {
                return ResourceManager.GetString("InternalConsistencyOfClassModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of component model.
        /// </summary>
        public static string InternalConsistencyOfComponentModel {
            get {
                return ResourceManager.GetString("InternalConsistencyOfComponentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of interaction model.
        /// </summary>
        public static string InternalConsistencyOfInteractionModel {
            get {
                return ResourceManager.GetString("InternalConsistencyOfInteractionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of ui design.
        /// </summary>
        public static string InternalConsistencyOfUiDesign {
            get {
                return ResourceManager.GetString("InternalConsistencyOfUiDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal consistency of use case model.
        /// </summary>
        public static string InternalConsistencyOfUseCaseModel {
            get {
                return ResourceManager.GetString("InternalConsistencyOfUseCaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuitive.
        /// </summary>
        public static string Intuitive {
            get {
                return ResourceManager.GetString("Intuitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will use parallels.
        /// </summary>
        public static string ItWillUseParallels {
            get {
                return ResourceManager.GetString("ItWillUseParallels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages supported.
        /// </summary>
        public static string LanguagesSupported {
            get {
                return ResourceManager.GetString("LanguagesSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveraging parallelism.
        /// </summary>
        public static string LeveragingParallelism {
            get {
                return ResourceManager.GetString("LeveragingParallelism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load capacity.
        /// </summary>
        public static string LoadCapacity {
            get {
                return ResourceManager.GetString("LoadCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizability.
        /// </summary>
        public static string Localizability {
            get {
                return ResourceManager.GetString("Localizability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiability by it specialists.
        /// </summary>
        public static string ModifiabilityByItSpecialists {
            get {
                return ResourceManager.GetString("ModifiabilityByItSpecialists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modularity.
        /// </summary>
        public static string Modularity {
            get {
                return ResourceManager.GetString("Modularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation configurability.
        /// </summary>
        public static string NavigationConfigurability {
            get {
                return ResourceManager.GetString("NavigationConfigurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature.
        /// </summary>
        public static string Nomenclature {
            get {
                return ResourceManager.GetString("Nomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-contradictory requirements.
        /// </summary>
        public static string Non_ContradictoryRequirements {
            get {
                return ResourceManager.GetString("Non-ContradictoryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string Payload {
            get {
                return ResourceManager.GetString("Payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portability.
        /// </summary>
        public static string Portability {
            get {
                return ResourceManager.GetString("Portability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation customizability.
        /// </summary>
        public static string PresentationCustomizability {
            get {
                return ResourceManager.GetString("PresentationCustomizability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing efficiency.
        /// </summary>
        public static string ProcessingEfficiency {
            get {
                return ResourceManager.GetString("ProcessingEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors.
        /// </summary>
        public static string ProcessingErrors {
            get {
                return ResourceManager.GetString("ProcessingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing testability.
        /// </summary>
        public static string ProcessingTestability {
            get {
                return ResourceManager.GetString("ProcessingTestability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship flexibility.
        /// </summary>
        public static string RelationshipFlexibility {
            get {
                return ResourceManager.GetString("RelationshipFlexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        public static string Reliability {
            get {
                return ResourceManager.GetString("Reliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement bindings.
        /// </summary>
        public static string RequirementBindings {
            get {
                return ResourceManager.GetString("RequirementBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements &quot;for future&quot;.
        /// </summary>
        public static string Requirements_ForFuture_ {
            get {
                return ResourceManager.GetString("Requirements\"ForFuture\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements testability.
        /// </summary>
        public static string RequirementsTestability {
            get {
                return ResourceManager.GetString("RequirementsTestability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving contradiction.
        /// </summary>
        public static string ResolvingContradiction {
            get {
                return ResourceManager.GetString("ResolvingContradiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks to user.
        /// </summary>
        public static string RisksToUser {
            get {
                return ResourceManager.GetString("RisksToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        public static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalability.
        /// </summary>
        public static string Scalability {
            get {
                return ResourceManager.GetString("Scalability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic correctness.
        /// </summary>
        public static string SemanticCorrectness {
            get {
                return ResourceManager.GetString("SemanticCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software portability.
        /// </summary>
        public static string SoftwarePortability {
            get {
                return ResourceManager.GetString("SoftwarePortability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software stability.
        /// </summary>
        public static string SoftwareStability {
            get {
                return ResourceManager.GetString("SoftwareStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code modifiability.
        /// </summary>
        public static string SourceCodeModifiability {
            get {
                return ResourceManager.GetString("SourceCodeModifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources of requirements.
        /// </summary>
        public static string SourcesOfRequirements {
            get {
                return ResourceManager.GetString("SourcesOfRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification completeness.
        /// </summary>
        public static string SpecificationCompleteness {
            get {
                return ResourceManager.GetString("SpecificationCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specificity of requirements.
        /// </summary>
        public static string SpecificityOfRequirements {
            get {
                return ResourceManager.GetString("SpecificityOfRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        public static string Stability {
            get {
                return ResourceManager.GetString("Stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State model and class model consistency.
        /// </summary>
        public static string StateModelAndClassModelConsistency {
            get {
                return ResourceManager.GetString("StateModelAndClassModelConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State model completeness.
        /// </summary>
        public static string StateModelCompleteness {
            get {
                return ResourceManager.GetString("StateModelCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State model internal consistency.
        /// </summary>
        public static string StateModelInternalConsistency {
            get {
                return ResourceManager.GetString("StateModelInternalConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System completeness.
        /// </summary>
        public static string SystemCompleteness {
            get {
                return ResourceManager.GetString("SystemCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testability.
        /// </summary>
        public static string Testability {
            get {
                return ResourceManager.GetString("Testability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threats from other systems.
        /// </summary>
        public static string ThreatsFromOtherSystems {
            get {
                return ResourceManager.GetString("ThreatsFromOtherSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threats to other systems.
        /// </summary>
        public static string ThreatsToOtherSystems {
            get {
                return ResourceManager.GetString("ThreatsToOtherSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type flexibility.
        /// </summary>
        public static string TypeFlexibility {
            get {
                return ResourceManager.GetString("TypeFlexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ui and functional model design consistency.
        /// </summary>
        public static string UiAndFunctionalModelDesignConsistency {
            get {
                return ResourceManager.GetString("UiAndFunctionalModelDesignConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ui and static model design consistency.
        /// </summary>
        public static string UiAndStaticModelDesignConsistency {
            get {
                return ResourceManager.GetString("UiAndStaticModelDesignConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usability completeness.
        /// </summary>
        public static string UsabilityCompleteness {
            get {
                return ResourceManager.GetString("UsabilityCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable scalability.
        /// </summary>
        public static string UsableScalability {
            get {
                return ResourceManager.GetString("UsableScalability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-friendliness.
        /// </summary>
        public static string User_Friendliness {
            get {
                return ResourceManager.GetString("User-Friendliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assistance.
        /// </summary>
        public static string UserAssistance {
            get {
                return ResourceManager.GetString("UserAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User errors.
        /// </summary>
        public static string UserErrors {
            get {
                return ResourceManager.GetString("UserErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User modifiability.
        /// </summary>
        public static string UserModifiability {
            get {
                return ResourceManager.GetString("UserModifiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User risks.
        /// </summary>
        public static string UserRisks {
            get {
                return ResourceManager.GetString("UserRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
    }
}
