//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestRSX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestRSX.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Start.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Title&gt;.
        /// </summary>
        public static string EmptyProjectTitle {
            get {
                return ResourceManager.GetString("EmptyProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file content:.
        /// </summary>
        public static string ExcelFileContent_ {
            get {
                return ResourceManager.GetString("ExcelFileContent_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files|*.xlsx;*.xlsm;*.xls.
        /// </summary>
        public static string ExcelFilesFilter {
            get {
                return ResourceManager.GetString("ExcelFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Excel files (*.xls)|*.xls.
        /// </summary>
        public static string ExcelXlsFilesFilter {
            get {
                return ResourceManager.GetString("ExcelXlsFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook files (*.xlsx)|*.xlsx.
        /// </summary>
        public static string ExcelXlsxFilesFilter {
            get {
                return ResourceManager.GetString("ExcelXlsxFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook with macros files (*.xlsm)|*.xlsm.
        /// </summary>
        public static string ExcelXslmFilesFilter {
            get {
                return ResourceManager.GetString("ExcelXslmFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Content Preview:.
        /// </summary>
        public static string FileContentPreview_ {
            get {
                return ResourceManager.GetString("FileContentPreview_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade scale.
        /// </summary>
        public static string GradeScale {
            get {
                return ResourceManager.GetString("GradeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quality factors defined.
        /// </summary>
        public static string NoFactorsDefined {
            get {
                return ResourceManager.GetString("NoFactorsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest XML files (*.qxml)|*.qxml.
        /// </summary>
        public static string QuestFilesFilter {
            get {
                return ResourceManager.GetString("QuestFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Excel file as ....
        /// </summary>
        public static string SaveExcelFileAs {
            get {
                return ResourceManager.GetString("SaveExcelFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as ....
        /// </summary>
        public static string SaveFileAs {
            get {
                return ResourceManager.GetString("SaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Quest file as ....
        /// </summary>
        public static string SaveQuestFileAs {
            get {
                return ResourceManager.GetString("SaveQuestFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file:.
        /// </summary>
        public static string SelectedFile_ {
            get {
                return ResourceManager.GetString("SelectedFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file:.
        /// </summary>
        public static string SelectFile_ {
            get {
                return ResourceManager.GetString("SelectFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        public static string XmlFilesFilter {
            get {
                return ResourceManager.GetString("XmlFilesFilter", resourceCulture);
            }
        }
    }
}
